### ISSUE TITLE
Version of Pytorch used.

### ISSUE THREAD

**Issue by Supritam0411** [timbmg/VAE-CVAE-MNIST#2]
Can you please reveal the Pytorch version used to code CVAE?

**Comment by timbmg** [comment]
Should be 0.3.1

**Comment by Supritam0411** [comment]
Thanks!

**Comment by Supritam0411** [comment]
@timbmg  as suggested I have used pytorch 0.3.1 with cuda 8.0: 

> pytorch                   0.3.1           py36_cuda8.0.61_cudnn7.1.2_3    pytorch

It would be really helpful if you could share your environment you used to build the code as I am still facing some errors because of python version
The current issue is:

> AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/somabiswas/anaconda3/envs/CVAE_pytorch/lib/python3.6/site-packages/torch/_utils.py'>

This issue is similar to https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560

**Comment by timbmg** [comment]
Could you share the full error track?

**Comment by Supritam0411** [comment]
When I run "python train.py --conditional" I get this error:

> /home/somabiswas/anaconda3/envs/CVAE_pytorch/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> Traceback (most recent call last):
>   File "train.py", line 143, in <module>
>     main(args)
>   File "train.py", line 33, in main
>     datasets['train'] = MNIST(root='data', train=True, transform=transforms.ToTensor(), download=True)
>   File "/home/somabiswas/anaconda3/envs/CVAE_pytorch/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 54, in __init__
>     os.path.join(self.root, self.processed_folder, self.training_file))
>   File "/home/somabiswas/anaconda3/envs/CVAE_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
>     return _load(f, map_location, pickle_module)
>   File "/home/somabiswas/anaconda3/envs/CVAE_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 420, in _load
>     result = unpickler.load()
> AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/somabiswas/anaconda3/envs/CVAE_pytorch/lib/python3.6/site-packages/torch/_utils.py'>
>

**Comment by timbmg** [comment]
I see, so its actually coming from torchvision. What version are you using? Maybe I can recreate. Also, are you certain you're executing pytorch 0.3.1? Because `_rebuild_tensor_v2` did not exist in that version (see here: https://github.com/pytorch/pytorch/blob/v0.3.1/torch/_utils.py).

**Comment by mitkina** [comment]
Hello,

I have the same error! What version of torchvision should we be using? I have pytorch 0.3.1.

Thanks!

**Comment by timbmg** [comment]
I just updated some stuff to new pytorch v1 and also added requirements.txt. Hope this helps! Let me know if you run into any problems!
