### ISSUE TITLE
Hello! About the latent space figure

### ISSUE THREAD

**Issue by HuMingqi** [timbmg/VAE-CVAE-MNIST#3]
I also evaluated the similar phenomena about the **Diffuse** latent space by CVAE, It is obviously different from the VAE model. Do you know which published paper researched on it or had similar figures with yours?

**Comment by timbmg** [comment]
I don't know about papers, but these two blog posts also visualize the latent space:
[https://wiseodd.github.io/techblog/2016/12/17/conditional-vae/](https://wiseodd.github.io/techblog/2016/12/17/conditional-vae/)
[http://nnormandin.com/science/2017/07/01/cvae.html](http://nnormandin.com/science/2017/07/01/cvae.html)

**Comment by HuMingqi** [comment]
Thanks for your reply!
