### ISSUE TITLE
normal distribution sampling error

### ISSUE THREAD

**Issue by zaocan666** [timbmg/VAE-CVAE-MNIST#7]
I am afraid there exists a bug in line 42 of models.py
`eps = torch.randn_like(std)`
torch.randn_like sample from uniform distribution, should have been normal distribution

**Comment by timbmg** [comment]
According to the [docs](torch.randn_like) torch.randn_like samples from normal distribution.

> Returns a tensor with the same size as input that is filled with random numbers from a **normal distribution** with mean 0 and variance 1

**Comment by zaocan666** [comment]
Sorry to bother, it was my fault. I mistook randn_like with rand_like.
